version: "2"

services:
    cdbookstore:
        image: agoncal/cdbookstore:jar
        ports:
            - 8080:8080
    topbooks:
        image: agoncal/topbooks:jar
        ports:
            - 8082:8082
    topcds:
        image: agoncal/topcds:jar
        ports:
            - 8081:8081
