version: "3"
services:
    rest-book:
        image: "agoncal/book:1.0-SNAPSHOT"
        ports:
            - "8702:8702"
        depends_on:
            - kafka
        environment:
            - ORG_AGONCAL_TALK_QUARKUS_BOOK_NUMBERPROXY_MP_REST_URL=http://rest-number:8701
            - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    rest-number:
        image: "agoncal/number:1.0-SNAPSHOT"
        ports:
            - "8701:8701"
    book-fallback:
        image: "agoncal/book-fallback:1.0-SNAPSHOT"
        ports:
            - "8080:8080"
        depends_on:
            - kafka
        environment:
            - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    zookeeper:
        image: strimzi/kafka:0.11.3-kafka-2.1.0
        command: [
                "sh", "-c",
                "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
            - "2181:2181"
        environment:
            LOG_DIR: /tmp/logs

    kafka:
        image: strimzi/kafka:0.11.3-kafka-2.1.0
        command: [
                "sh", "-c",
                "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
        ]
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            LOG_DIR: "/tmp/logs"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
