services:
    postgres:
        image: "postgres:14.6"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "books_database"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
