services:
    postgres:
        image: "postgres:13.4"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: books_database
            POSTGRES_USER: book
            POSTGRES_PASSWORD: book
